message: This is the file that contains the development properties TODAY AGAIN on 17/Jan
spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
